### ISSUE TITLE
東京

### ISSUE THREAD

**Issue by qaconst** [MeetingTimeService2/MeetingTimeCircle#21]
@devdrunk :bow:

[00 仕様書.pdf](https://github.com/MeetingTimeService2/MeetingTimeCircle/files/410163/00.pdf)

![screen shot 2016-08-10 at 10 25 54](https://cloud.githubusercontent.com/assets/20792410/17538927/d8a05768-5ee4-11e6-8a21-aebd3ff030c2.png)

☝️ ここを直します

**Comment by ghost** [comment]
@qaconst わかりました 👍
